# Site settings
title:        "Goodrocket-Jekyll"
description:  "Web development starting kit based on Jekyll and Gulp"


# URL configuration
url:          "http://domain.com" # the base hostname for the project, e.g. http://domain.com
baseurl:      ""  # the subpath of the project in production, e.g. /blog
permalink:    /:categories/:title/ # base url structure for posts


# Using temp folders to help Gulp do its job.
source:       .tmp/source
destination:  .tmp/build


# Include/exclude settings
exclude:      ["assets"]
include:      ["_pages"]


# Markdown settings
markdown:     kramdown


# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
